### 정상 송금
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 2,
  "toAccountId": 3,
  "amount": 10000
}

### 같은 계좌로 송금
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 1,
  "amount": 3000
}

### 잔액보다 많이 송금
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2,
  "amount": 99999999
}

### 존재하지 않는 계좌
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 999,
  "toAccountId": 2,
  "amount": 3000
}

#### 0보다 작은 금액 송금
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2,
  "amount": -3000
}

#### 송금 금액 누락
POST http:// localhost:8080/api/transfers
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2
}

#### 출금계좌 누락
POST http://localhost:8080/api/transfers
Content-Type: application/json

{
"toAccountId": 2,
"amount": 1000
}

#### 멱등성 조회
POST http://localhost:8080/api/transfers
Content-Type: application/json
Idempotency-Key: transfer-2-to-3-001

{
  "fromAccountId": 2,
  "toAccountId": 3,
  "amount": 3000
}

### 멱등성 조회2
POST http://localhost:8080/api/transfers
Content-Type: application/json
Idempotency-Key: conflict-api-test-001

{
  "fromAccountId": 2,
  "toAccountId": 3,
  "amount": 5000
}


#### 계좌 조회
GET http://localhost:8080/api/accounts

#### 송금내역 조회
GET http://localhost:8080/api/transfers

### 1번 계좌가 보낸 내역 조회
GET http://localhost:8080/api/transfers/sent/2

### 1번 계좌가 받은 내역 조회
GET http://localhost:8080/api/transfers/received/1

### 1번 계좌 전체 거래내역
GET http://localhost:8080/api/transfers/accounts/3

