### 사용자 생성
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "홍길동"
}


#### 전체 조회
#GET http://localhost:8080/api/users


POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "userId": 1
}

POST http://localhost:8080/api/accounts/1/deposit
Content-Type: application/json

{
  "amount": 10000
}